apiVersion: v1
kind: Service
metadata:
    name: vishnuazurepipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8888 
    selector:
        app: vishnuazurepipelinesjavascriptdocker